### ISSUE TITLE
Chess Games Analysis

### ISSUE THREAD

**Issue by guptavaibhav159** [mbiesiad/awesome-chess#16]
Can I add Some Chess Games with full Information about Games,Players and even the Moves the Player Played the Match with the Results?

**Comment by mbiesiad** [comment]
Hi @guptavaibhav159 Quite interesting idea! 🔥  Thank you for your message. You may if that the content does not violate any copyrights & please make sure how about GDPR in this case.

If everything is fine, please create a new Folder for the items (similar like it is with [media](https://github.com/mbiesiad/awesome-chess/tree/master/media) section) & link them to the main file (about.md).

Thanks! Best wishes 🦄

**Comment by guptavaibhav159** [comment]
Yeah Sure.

**Comment by mbiesiad** [comment]
If you have any questions, feel free to ask. Can I close this issue?

**Comment by guptavaibhav159** [comment]
Yup You May Close It. I will Post My PR soon.

**Comment by mbiesiad** [comment]
Cool, thanks for quick answer. Keep in touch!
